"""Mission Report Generation API"""
from fastapi import APIRouter, HTTPException
from services.satellite_service import satellite_service
from .satellite_analysis import handle_satellite_click, debris_service
from core.utils.response import success_response, error_response
import base64

router = APIRouter()

@router.get("/mission-report/{satellite_id}")
async def generate_mission_report(satellite_id: str):
    """Generate PDF mission report (base64) with risk snapshot and horizon curve."""
    try:
        sat = await satellite_service.get_satellite_by_id(satellite_id)
        if not sat:
            raise HTTPException(status_code=404, detail="Satellite not found")
        debris_list = await debris_service.get_all_debris(limit=1000)
        debris_with_coords = [d for d in debris_list if all(f in d for f in ["x","y","z","vx","vy","vz"])]
        analysis = handle_satellite_click(sat=sat, debris_list=debris_with_coords, top_n=3, include_maneuver=True) if debris_with_coords else {"nearest": []}

        # Build simple risk horizon (reuse endpoint logic inline)
        import math
        base_prob = analysis.get("nearest", [{}])[0].get("model1_risk", {}).get("probability", 0.0)
        curve = []
        for h in range(0, 25, 5):
            prob = base_prob * math.exp(- h / 36.0)
            curve.append((h, prob))

        # Create PDF using fpdf
        from fpdf import FPDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=16)
        pdf.cell(0, 10, f"Mission Report: {sat.get('name', sat.get('id'))}", ln=1)
        pdf.set_font("Arial", size=11)
        pdf.cell(0, 8, f"Satellite ID: {sat.get('id')}", ln=1)
        pdf.cell(0, 8, f"Altitude (km): {sat.get('altitude_km')}", ln=1)
        pdf.cell(0, 8, f"Latitude/Longitude: {sat.get('latitude')} / {sat.get('longitude')}", ln=1)
        pdf.ln(4)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, "Top Threats", ln=1)
        pdf.set_font("Arial", size=10)
        for n in analysis.get("nearest", []):
            prob = n.get('model1_risk', {}).get('probability')
            dist = n.get('distance_now_km')
            debris_name = n.get('debris', {}).get('name') or n.get('debris', {}).get('id')
            pdf.cell(0, 6, f"Debris {debris_name} | Dist {dist:.2f} km | Prob {(prob*100):.1f}%", ln=1)
        pdf.ln(4)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, "Risk Horizon (hrs vs probability %)", ln=1)
        pdf.set_font("Arial", size=10)
        for h, p in curve:
            pdf.cell(0, 6, f"{h:>2}h : {(p*100):.1f}%", ln=1)
        pdf.ln(4)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, "Generated By Orbit Shield", ln=1)

        pdf_bytes = pdf.output(dest='S').encode('latin-1')
        encoded = base64.b64encode(pdf_bytes).decode('ascii')
        return success_response({"pdf_base64": encoded, "filename": f"mission_report_{sat.get('id')}.pdf"})
    except HTTPException:
        raise
    except Exception as e:
        return error_response(f"Report generation failed: {e}")